# Generated by Django 3.2.16 on 2023-01-12 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('status', models.TextField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.BooleanField(default=False)),
                ('batch', models.CharField(max_length=10, unique=True)),
                ('booked_in', models.DateField(auto_now_add=True)),
                ('comments', models.TextField(blank=True)),
                ('status', models.TextField(choices=[('To Test', 'To Test'), ('Approved', 'Approved')], default='To Test')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.material')),
            ],
            options={
                'ordering': ['booked_in'],
            },
        ),
    ]
