# Generated by Django 3.2.16 on 2023-01-22 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_batch_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.material'),
        ),
    ]
