# Generated by Django 3.2.16 on 2023-01-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_batch_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='comments',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
