# Generated by Django 3.2.16 on 2023-01-12 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('status', models.TextField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('status', models.TextField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active')),
            ],
        ),
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('comment', models.TextField(blank=True)),
                ('status', models.TextField(choices=[('To Do', 'To Do'), ('Completed', 'Completed')], default='To Do')),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.analyst')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.test')),
            ],
            options={
                'ordering': ['test_date'],
            },
        ),
    ]
