# Generated by Django 3.2.16 on 2023-01-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20230122_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workload',
            name='comment',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
