# Generated by Django 3.2.16 on 2023-02-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_alter_workload_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyst',
            name='work_id',
            field=models.CharField(default=1, max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analyst',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
